---
- hosts: Test-server
  become: true 
  tasks:
    - name: apt update
      command: sudo apt-get update
    - name: install docker
      apt:
        pkg: docker.io
        state: present
        #command: sudo apt install docker.io
    - name: start docker
      service:
        name: docker
        state: started
        enabled: true
        
    - name: Deploy InsureMe App Container
      command: docker run -itd -p 8081:8081 parthasarathy89/Insureme:1.0
      state: started
        
